---
- name: Deploy postgres on ansiblenode2.example.com
  hosts: db
  vars_files:
    - files/secrets.yml
  roles:
    - role: database
      database_name: "{{ mezzanine_proj_name }}"
      database_user: "{{ mezzanine_proj_name }}"

- name: Deploy mezzanine on ansiblenode3.example.com
  hosts: web
  vars_files:
    - files/secrets.yml
  roles:
    - role: mezzanine
      database_host: "{{ hostvars['ansiblenode2.example.com'].ansible_enp0s8.ipv4.address }}"
      live_hostname: 192.168.56.106.xip.io
      domains:
        - 192.168.56.106.xip.io
        - www.192.168.56.106.xip.io


