---
# vars file for mezzanine
mezzanine_user: "{{ ansible_user }}"
mezzanine_group: "{{ ansible_user }}"
mezzanine_venv_home: "{{ ansible_env.HOME }}/.virtualenvs"
mezzanine_venv_path: "{{ mezzanine_venv_home }}/{{ mezzanine_proj_name }}"
mezzanine_proj_path: "{{ ansible_env.HOME }}/mezzanine/{{ mezzanine_proj_name }}"
mezzanine_settings_path: "{{ mezzanine_proj_path }}/{{ mezzanine_proj_app }}"
mezzanine_repo_url: https://github.com/jyothish2607/mezzanine_example.git
mezzanine_reqs_path: requirements.txt
mezzanine_python: "{{ mezzanine_venv_path }}/bin/python"
mezzanine_manage: "{{ mezzanine_python }} {{ mezzanine_proj_path }}/manage.py"
mezzanine_conf_path: /etc/nginx/conf
mezzanine_gunicorn_port: 8000
mezzanine_gunicorn_exec: "{{ mezzanine_venv_path }}/bin/gunicorn"
mezzanine_gunicorn_socket: "{{ mezzanine_proj_path }}/gunicorn.sock"
mezzanine_gunicorn_procname: gunicorn_mezzanine
mezzanine_num_workers: 5
